baseURL = "https://albert-tuan.github.io/"
languageCode = "en-us"
theme = "terminal"
title = "Albert Tuan's Blog"
paginate = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Albert Tuan's Blog"

    [languages.en.params]
      subtitle = "SecOps & Reversing Blog"
      owner = "Albert Tuan"
      keywords = "security, reversing, malware analysis"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Albert's Blog"
        logoHomeLink = "/"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

[module]
  replacements = "github.com/panr/hugo-theme-terminal/v4 -> themes/terminal"
